### ISSUE TITLE
Delightful TTS implementation 

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#1715]
Paper: https://arxiv.org/abs/2110.12612

👑 @loganhart420 is going to do the heavy lifting !!!

We can discuss here how we want to go about it.

**Comment by dunky11** [comment]
Thanks for opening the issue! Pre-training the model will take me roughly one more week. Afterward, I will refactor the code, and get the project into a usable state, then I will implement this into coqui, so it will probably take me 6+ weeks. 

Some info about the model: It's based upon DelightfulTTS with some modifications. Many components of the model weren't fully explained [in the paper](https://arxiv.org/abs/2110.12612). They especially didn't get into details about both the phoneme and utterance level prosody encoder as well as hyperparameters used, so their implementation was heavily influenced by [Comprehensive-Transformer-TTS](https://github.com/keonlee9420/Comprehensive-Transformer-TTS).  The model also uses a different scheme to provide both language and speaker embeddings. The scheme of DelightfulTTS may have worked for the blizzard challenge but didn't work when using more speakers/languages.

For the G2P model, I used [DeepPhonemizer](https://github.com/as-ideas/DeepPhonemizer), which implements [Transformer-based Grapheme-to-Phoneme Conversion](https://arxiv.org/abs/2004.06338), and increased the parameter count to ~23M. The G2P model is trained on the global phone sets of [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/) in the following languages:

- English
- German
- French
- Castilian Spanish
- Russian
- Polish 
- Bulgarian
- Czech
- Croatian
- European Portuguese
- Swedish
- Thai
- Turkish
- Ukrainian

Also, I increased the parameter count of DelightfulTTS to ~120M, otherwise, it would underfit the dataset. The dataset is ~20% stuff from public datasets like LibriTTS (100h and 360h split) and VCTK and ~80% stuff crawled by me. If you want to see some statistics about the dataset, you can [click here](https://montreal-forced-aligner.readthedocs.io/en/latest/). 

The purpose of the model is to be fine-tuned on smaller datasets. It should provide a way to create TTS models in languages with limited data. It can also be used to code-switch: Since the model was pre-trained in English, German, French, Spanish, Russian and Polish voices it can be used to fine-tune the model on an English voice and then make it speak the other languages.

The parameter count may seem intimidating for a TTS model, but it can be fine-tuned without a problem on 6GB of VRAM using gradient accumulation. Also since the architecture is FastSpeech-based, and avoids autoregression, both training and inference are relatively quick and stable. 

UnivNet is used as vocoder, but any vocoder that shares its STFT configuration should do its job. 

In the future, I will further increase the size of the dataset, especially for the languages which contain no data yet. I also plan on further increasing the size of the model, since the current model underfits the dataset.  Then I will try to create a smaller model using knowledge distillation.

I really hope the model turns out fine, I will probably fine-tune it tomorrow on an English single-speaker dataset to check how well it speaks in the other languages, even though it hasn't fully pre-trained, since I'm always impatient :)

If you are interested in the progress, check out [VoiceSmith](https://github.com/dunky11/voicesmith) (still a WIP) which provides a GUI to fine-tune the multilingual model and preprocess multilingual TTS datasets.

**Comment by dunky11** [comment]
I also noticed the multilingual G2P stuff and unusual phone set (phone set from [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/)) will probably make it a pain to implement this into coqui. It's probably better to implement the English-only version which was trained on ARPABET, I will develop that one alongside the multilingual one anyway. I have a colab for inference of that one [here](https://colab.research.google.com/drive/1zh6w_TpEAyr_UIojiLmt4ZdYLWeap9mn#scrollTo=vQCA50dao0Mt).

**Comment by erogol** [comment]
Samples above are impressive. TR samples are like someone German speaking TR :)

**Comment by dunky11** [comment]
Just noticed coqui already has support for multiple languages, that is nice. It doesn't really matter which G2P model we use, we just need a way to extract the phoneme durations using a forced aligner for example. I see you implemented FastSpeech and FastPitch. How did you extract phoneme durations? Or did you differ from the original implementation using unsupervised durations (since you implemented https://arxiv.org/pdf/2108.10447.pdf)?

**Comment by erogol** [comment]
We learn durations unsupervised in different ways one of which is that paper. It is called ```AlignerNet``` in 🐸TTS.

**Comment by jinfagang** [comment]
Hello, guys. I saw there so many languages, but just not Chinese, does there any plan to support Chinese?

**Comment by neurlang** [comment]
Czech is understandable.

**Comment by erogol** [comment]
👑 @loganhart420 will continue implementing this.

**Comment by jinfagang** [comment]
Does it avaiable for now

**Comment by loganhart420** [comment]
> Does it avaiable for now

I'm currently training the pretrained models, the pr to follow along is here: https://github.com/coqui-ai/TTS/pull/2095

**Comment by agilebean** [comment]
Can someone please summarize the differences between Voicesmith by @dunky11  and the current repo of TTS by coqui-ai?

**Comment by ludwikbukowski** [comment]
Polish is awesome!
When would it be ready? Can I download the model even if its WIP ?

**Comment by loganhart420** [comment]
> Polish is awesome!
> When would it be ready? Can I download the model even if its WIP ?

you can clone the branch right now and train from scratch. I've got a working ljspeech and vctk model working so it should work for single and multi speaker datasets.

**Comment by raul-parada** [comment]
how can I voice clone my own voice (spanish) with this tool? please, some steps. thanks

**Comment by SyGen899** [comment]
@loganhart420 thanks so much for this implementation, Im not sure if this is the most appropriate place to ask about this, but I am running into issues trying to start training. the first issue was with getting the numerical speaker ids from names, but I took the code from vits here and it seemed to work, the other issue Im facing now is below. Im pretty new to this so its out of my depth what  could be the problem, are you able to shed some light on how to fix this? thanks.

! Run is kept in ./delightful/delightful_tts_e2e_ljspeech-January-17-2023_07+05AM-0000000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/trainer/trainer.py", line 1686, in fit
    self._fit()
  File "/usr/local/lib/python3.8/dist-packages/trainer/trainer.py", line 1639, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.8/dist-packages/trainer/trainer.py", line 1393, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/usr/local/lib/python3.8/dist-packages/trainer/trainer.py", line 1239, in train_step
    outputs, loss_dict_new, step_time = self.optimize(
  File "/usr/local/lib/python3.8/dist-packages/trainer/trainer.py", line 1083, in optimize
    scaler.scale(loss_dict["loss"]).backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by iamkhalidbashir** [comment]
Will there be a pre-trained model available for it? (for fine-tuning)

**Comment by jinfagang** [comment]
Does delightful tts support mandrain now?

**Comment by iamkhalidbashir** [comment]
> > Does it avaiable for now
> 
> I'm currently training the pretrained models, the pr to follow along is here: #2095

Can you share the pre-trained models?

**Comment by ludwikbukowski** [comment]
yeah, sharing some of the models would be highly appreciated :)

**Comment by iamkhalidbashir** [comment]
is this PR for Delightful TTS 1 or Delightful TTS 2 (https://arxiv.org/abs/2207.04646)

**Comment by erogol** [comment]
its 1

**Comment by iamkhalidbashir** [comment]
Any possibility to change it to 2 as it requires small changes but give better MOS score that 1 as in the paper

**Comment by iamkhalidbashir** [comment]
The PR is still open though
https://github.com/coqui-ai/TTS/pull/2095

**Comment by catselectro** [comment]
> I fine-tuned the model on the voices of Twilight Sparkle (~6000 samples, My Little Pony) and Demoman (~500 samples, Team Fortress 2) now. There is definitely still a lot of work that needs to be done but I think it shows that it's possible to pre-train a model in a bunch of languages and then make it speak languages not seen in the fine-tuning dataset.
> 
> Original: Twilight: https://vocaroo.com/1dI8o6NZqi9e Demoman: https://vocaroo.com/1dokyJI1Kt0u
> 
> English (in pre-training dataset, in fine-tuning dataset): Twilight: https://vocaroo.com/19M1jbIR8aDW Demoman: https://vocaroo.com/1g0pnFJ3jqNK
> 
> German (in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/15jWTR3wpSiA Demoman: https://vocaroo.com/1aInIEAfiJgb
> 
> French (in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/16cc8wjg8UKn Demoman: https://vocaroo.com/1czkTPaQm8ir
> 
> Spanish (in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1oUORqiRiJOY Demoman: https://vocaroo.com/1iXKvd5GaXlf
> 
> Russian (in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1h6k4mUdMQ0u Demoman: https://vocaroo.com/1doXkCsPyoM5
> 
> Polish (in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1eklCtLEuqPg Demoman: https://vocaroo.com/12om7gCZH5Zd
> 
> The **languages below should not** work since the model has not seen them in both pre-training and fine-tuning, I will include them anyway.
> 
> Bulgarian (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1dC5qGhPn4op Demoman: https://vocaroo.com/1epSvuv04Tug
> 
> Czech (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1f8yMHYHvFwo Demoman: https://vocaroo.com/19zHsVku5My1
> 
> Croatian (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1dAlyJqd6pNj Demoman: https://vocaroo.com/1o0qrTSGiMwb
> 
> European Portuguese (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1d9K6XegabUO Demoman: https://vocaroo.com/1h7jCNhbuAoG
> 
> Swedish (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/15ma7yF5OhZa Demoman: https://vocaroo.com/1cP4I6JOsfqX
> 
> Thai (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1lIZW5rT8sbc Demoman: https://vocaroo.com/12YFcNHHnDzH
> 
> Turkish (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/1h56wternaDp Demoman: https://vocaroo.com/1gIOQTY6mPne
> 
> Ukrainian (not in pre-training dataset, not in fine-tuning dataset): Twilight: https://vocaroo.com/150bIrTIDLaa Demoman: https://vocaroo.com/14PmdpuAHOKj

Hi Tim, is there any chance you could share that pre-trained model in multiple languages? Thank you!!
