### ISSUE TITLE
[Bug] Multiple linked copies of libomp.dylib cause commands to fail

### ISSUE THREAD

**Issue by theSherwood** [coqui-ai/TTS#1793]
### Describe the bug

Any use of `tts` cli fails with:

```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
Abort trap: 6
```

### To Reproduce

1. Run `pip3 install tts`
2. Run any command with `tts` such as `tts --list_models`
3. See error

### Expected behavior

The `tts` commands, such as `tts --list_models`, should run successfully.

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.12.0",
        "TTS": "0.7.1",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "i386",
        "python": "3.9.12",
        "version": "Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64"
    }
}
```
```

**Comment by p0p4k** [comment]
A little Google search points me to this [link](https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial#:~:text=when%20using%20matplotlib%3A-,Error%20%2315%3A%20Initializing%20libiomp5.,performance%20or%20cause%20incorrect%20results) . Try the solutions mentioned there.

**Comment by theSherwood** [comment]
@p0p4k I can't find much here that seems applicable. I'm just wanting to run tts as a command-line tool. Do I need to have a conda environment to run it? I've tried uninstalling and re-installing various packages, but that is basically a shot in the dark as it's unclear to me what the dependencies of the tool are and what kind of python environment is required to run it.

**Comment by p0p4k** [comment]
Try using Google colab then instead.

**Comment by p0p4k** [comment]
@theSherwood Also, if you read the second line in error ->
`OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/`

- You can see :
  _As an unsafe, unsupported, undocumented workaround you can set the environment variable **KMP_DUPLICATE_LIB_OK=TRUE**_

- So maybe try this :
  ```
  import os
  os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
  ```

**Comment by theSherwood** [comment]
Thanks @p0p4k . What I ended up doing was just putting together a docker container running ubuntu and everything runs without issue.

**Comment by erogol** [comment]
Seemingly this issue is solved. Thanks @p0p4k @theSherwood
