### ISSUE TITLE
[Feature request] tts from phonemes instead of words?

### ISSUE THREAD

**Issue by asiletto** [coqui-ai/TTS#2235]
I have a text which contains a foreign word. Using the english model, the word is spoken as it would be english.

`tts --model_name tts_models/en/vctk/vits --speaker_idx p273 --out_path test_gobekli_tepe.wav --text "At a casual glance, Gobekli Tepe looks like an ordinary hill."
`
I could obviously use the corrispondent model just for the foreign part, but the voice would be different.

Ideally I'd like to do something like this:

`tts --model_name tts_models/en/vctk/vits --speaker_idx p273 --out_path test_gobekli_tepe.wav --text "At a casual glance, <phonetic>ɟœbecˈli teˈpe</phonetic> looks like an ordinary hill."
`

Or even just be able to give in input just the phonemes (which I am not sure is correct, but I could approximate it with multiple tries)

`tts --model_name tts_models/en/vctk/vits --speaker_idx p273 --out_path test_gobekli_tepe.wav --phoneme "ɟœbecˈli teˈpe"
`
Or can someone suggest an alternative to get "Gobekli Tepe" pronunced correctly with an english model?

**Comment by WeberJulian** [comment]
Hey, two response to that.

First espeak as a phonemizer is supposed to do that for the words it knows, for exemple "deja vu" with language set to english, is gonna be replaced by French phonemes.

Second, I guess the solution for that would be SSML, we've stop working on that because it's not a priority for now, but you can check it out here: https://github.com/coqui-ai/TTS/pull/1452/files

**Comment by asiletto** [comment]
Thank you, I'll look at the pull 1452
