### ISSUE TITLE
[Bug] No grad in YourTTS speaker encoder

### ISSUE THREAD

**Issue by Tomiinek** [coqui-ai/TTS#2348]
### Describe the bug

Hello guys (CC: @Edresson @WeberJulian), when going through YourTTS code & paper, I noticed that you are calculating the inputs for the speaker encoder with no grads:
https://github.com/coqui-ai/TTS/blob/d46fbc240ccf21797d42ac26cb27eb0b9f8d31c4/TTS/encoder/models/resnet.py#L153-L200

I suspect that the speaker encoder is not producing any gradients, and the speaker consistency loss has no effect.
It looks like this happens:
- forward gets x with grads
- the spectrogram is extracted via `torch_spec` with no grads
- the output of the speaker encoder has requires grad False (and would produce an exception when you called backward on it since it did not keep activations for grad calculation), but is added to the total loss (which has requires grads se to True)
- so the call to `loss.backward()` works as usually, but the speaker encoder does not contribute to the gradients flowing to the generator at all

Could you please check on that? 

### To Reproduce

``` python
import torch

a = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)

with torch.no_grad():
     c = a + b

d = c + 1
e = a + d
e.backward()

print(a.grad) # 1
print(b.grad) # not set

d.backward() # RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

### Environment

```shell
Just reading the code and asking :)
```

**Comment by WeberJulian** [comment]
Nice catch, that's concerning. Thanks for reporting it. We'll look more into it but it looks like you are right.
This `torch.no_grad` doesn't affect the speaker encoder during training because there is no parameter before it. But in our case, using the original implementation for SCL, the TTS parameters are before this `torch.no_grad`. I guess in the paper the slightly better SECS score are explained by the extra training steps...

**Comment by Edresson** [comment]
Nice catch. Indeed it is an issue. I will submit a PR to fix it.

**Comment by Tomiinek** [comment]
Thank you @Edresson 

Are you also planning to retrain the models and update the YourTTS paper on arxiv?  :innocent:

**Comment by Edresson** [comment]
> Thank you @Edresson
> 
> Are you also planning to retrain the models and update the YourTTS paper at least on arxiv? innocent

I think it is not worth because if we do it we will need to recompute the MOS and Sim-MOS. I'm thinking about  update the preprint, removing Speaker Consistency Loss from the methodology. And  given that the Speaker Consistency Loss had no effect on the results, Speaker Consistency Loss  experiments are equal than keep the model training per more 50k steps. In addition, I will try to retracting this issue on ICML published paper as well. Fortunately, It is a minor issue and the reported results  are not effected (only the method description that is wrong).

**Comment by Edresson** [comment]
@Tomiinek  Thanks so much for finding the bug and reporting it. I talked with all authors and the final decision was added a Erratum on [YourTTS Github repository](https://github.com/Edresson/YourTTS#erratum) and on the last page of the [preprint](https://arxiv.org/abs/2112.02418). It is done :).
