### ISSUE TITLE
[Feature request] Support for TortoiseTTS

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#2424]
**🚀 Feature Description**
Support for TortoiseTTS inference relying on the official implementation https://github.com/neonbjb/tortoise-tts

I also see some forks claiming faster inference. Maybe we can give them a try too. 

https://github.com/152334H/tortoise-tts-fast

**Comment by DaveJarvis** [comment]
See: https://git.ecker.tech/mrq/tortoise-tts/

**Comment by erogol** [comment]
WIP

**Comment by samhardyhey** [comment]
Thanks for prioritising this @erogol @manmay-nakhashi , just noted that the current [tortoise notebook](https://github.com/coqui-ai/TTS/blob/dev/notebooks/Tortoise.ipynb) is failing to import the tortoise TTS API like so:

```from TTS.tts.models.tortoise import TextToSpeech```

Thought to add to this existing issue/thread rather than open up a new one.

**Comment by erogol** [comment]
I think there is no texttospeech anymore. We'll remove the notebook. I don't think it is necessary anymore.  @manmay-nakhashi  what do you think? 

And I close this issue

**Comment by manmay-nakhashi** [comment]
@erogol I'll remove that
