### ISSUE TITLE
[Feature request] Implementation for FreeVC

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#2438]
**🚀 Feature Description**
Original implementation: https://github.com/OlaWod/FreeVC

We can use it in combination with any 🐸TTS model and make it speak with any voice aka faking voice cloning. 

**Additional context**

I'll initially implement only inference with the pre-trained models and later we can implement the training. It should be easy as it a quite the same as the VITS.

**Comment by rishubil** [comment]
I've tried using FreeVC, and I have to say the performance is quite impressive.
However, one thing that was disappointing is that when I tried using it with languages other than English, the intonation sounded unnatural, perhaps because the model was trained on the VCTK dataset.
If training becomes available in the future, it would be great to try fine-tuning the model.
I hope that implementation will become available someday.

**Comment by erogol** [comment]
Implementation for inference with a trained model is already available in the model zoo but forgot to close this

**Comment by treya-lin** [comment]
> Implementation for inference with a trained model is already available in the model zoo but forgot to close this

Hi, do we have the implementation for training in CoquiTTS now? Thanks a lot!

**Comment by jioaicoevision** [comment]
@erogol can we train freevc in coqui?
