### ISSUE TITLE
[Feature request] Start server in Docker container directly, without going via shell

### ISSUE THREAD

**Issue by chrisbward** [coqui-ai/TTS#2672]
Would be nice to be able to launch the server in one single command instead of dropping in to the interactive shell.

It's an extra step, but would like to automate this task.

So the following works;
```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash -v /home/user/.local/share/tts/:/root/.local/share/tts/ tts -h
```
But the below doesn't?
```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash -v /home/user/.local/share/tts/:/root/.local/share/tts/ tts --model_name tts_models/en/vctk/vits --use_cuda true
```

Unsure of alternative methods - very furstrating!

**Additional context**

**Comment by r4j4h** [comment]
Hi there,

I believe the shell environment is getting confused, can you try these two approaches? Hopefully one or both work for you:

1) use the bash entrypoint in a `sh -c "commands | here"` style:
```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash -v /home/user/.local/share/tts/:/root/.local/share/tts/ tts -c "tts --model_name tts_models/en/vctk/vits --use_cuda true"
```

2) use the `tts` binary as entrypoint and then just your arguments after the image:
```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint tts -v /home/user/.local/share/tts/:/root/.local/share/tts/ tts --model_name tts_models/en/vctk/vits --use_cuda true
```

**Comment by chrisbward** [comment]
Neither worked, and always defaults to --help, but may be because of the following line?
https://github.com/coqui-ai/TTS/blob/21a3f280dea7ab7c6381f5805589514bea86da4d/Dockerfile#L13

**Comment by r4j4h** [comment]
Oh, my apologies, I didn't understand your goal correctly.

That CMD line is actually only used when we don't provide anything after the image on the `docker run` command, so we are overriding it. The problem here is we are not starting the server: we need to re-create what you were doing in the shell to begin with.

Going by the [instructions to start the server in the readme](https://github.com/coqui-ai/TTS/tree/dev#docker-image) can you try the following?

1. use the bash entrypoint in a sh -c "commands | here" style:

```
docker run --rm -it -p 5002:5002  --entrypoint /bin/bash -v /home/user/.local/share/tts/:/root/.local/share/tts/ ghcr.io/coqui-ai/tts-cpu -c "python3 TTS/server/server.py --list_models tts --model_name tts_models/en/vctk/vits --use_cuda true"
```

2. use the _python_ binary as entrypoint and then after the image the python script and your arguments:

```
docker run --rm -it -p 5002:5002  --entrypoint python3 -v /home/user/.local/share/tts/:/root/.local/share/tts/ ghcr.io/coqui-ai/tts-cpu TTS/server/server.py --list_models tts --model_name tts_models/en/vctk/vits --use_cuda true
```
