### ISSUE TITLE
[Bug] Bark Model can not generate special sounds

### ISSUE THREAD

**Issue by BaiMoHan** [coqui-ai/TTS#3044]
### Describe the bug

 I have encountered an issue where the output I receive differs from the output shown in the official repository, even though I am using the same prompt that is provided. This discrepancy is creating confusion and making it difficult for me to understand and compare my results with the expected outcomes.
my code
```
from TTS.api import TTS
import time

# Load the model to GPU
# Bark is really slow on CPU, so we recommend using GPU.
tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=True)


text = """
    ♪ In the jungle, the mighty jungle, the lion barks tonight ♪
    """
tts.tts_to_file(text=text,
                file_path="output.wav",
                voice_dir="bark-voices/",
                speaker="en_speaker_9")
```
bark example code
```
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
    ♪ In the jungle, the mighty jungle, the lion barks tonight ♪
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)
  
# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)

```

TTS can not generate the song

### To Reproduce

python code
```
from TTS.api import TTS
import time

# Load the model to GPU
# Bark is really slow on CPU, so we recommend using GPU.
tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=True)


text = """
    ♪ In the jungle, the mighty jungle, the lion barks tonight ♪
    """
tts.tts_to_file(text=text,
                file_path="output.wav",
                voice_dir="bark-voices/",
                speaker="en_speaker_9")
```

### Expected behavior

generate the song

### Logs

```shell
no error outputs
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A10"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.17.8",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.13",
        "version": "#74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023"
    }
}
```

**Comment by Sharrnah** [comment]
@BaiMoHan
I think this is pretty much expected behaviour.

1. Bark is nondeterministic. That means that each call will result in different results. No matter what you do.
2. You are using a speaker npz file, where the original example does not and as such is more free to generate whatever your prompt wants. Try it again without a speaker NPZ file. (maybe a couple times) and you should get some singing eventually. But they will _always_ be different than the example in the official repository.

if the prompt without a speaker npz file resulted in some singing, you can save that history prompt as npz and use that for future generations, which will most likely result in every prompt you do afterwards with that npz file to sing.

**Comment by erogol** [comment]
I agree with @Sharrnah
