### ISSUE TITLE
[Bug] FileNotFoundError: [Errno 2] No such file or directory: ...config.json

### ISSUE THREAD

**Issue by Kzer-Za** [coqui-ai/TTS#3064]
### Describe the bug

`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/tts/tts_models--multilingual--multi-dataset--bark/config.json'`

### To Reproduce

1. `pip install TTS`
2. `tts --text "some text" --model_name "tts_models/multilingual/multi-dataset/bark" --out_path /some/path`
3. Ctrl-C 
4. `tts --text "some text" --model_name "tts_models/multilingual/multi-dataset/bark" --out_path /some/path`

### Expected behavior

The program should check whether it was completed successfully the first time and all the necessary files were downloaded/created, and if not, repeat the process for the missing files.

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.17.8",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.11.5",
        "version": "#1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:13:56 UTC 2023"
    }
}
```

**Comment by erogol** [comment]
You need to remove the folder if you break the download the first time.

**Comment by illtellyoulater** [comment]
After a few days using this project I've come to think it's the worst code base I've ever seen.

It's a massive pile of half working code full of frustrating bugs like the one here.  I've also seen seriously bad stuff like code trying to run stuff in the root dir and other unacceptable stuff like that gone unaddressed for years.

Or fatal bugs like the one reported here, where the installation of Barks fails silently and will never be attempted again just because of a download failing on first attempt... But the worst thing is that instead of putting an alert for serious issue like this in the README, that page is only modified to show how modern and cool and up-to-date this toolkit is being maintained....while under the hood entire layers of this project are falling apart.

The only good part seem to be the frog concept, but at this point, and with all the above said, all it's really starting to look more like some facade operation... I really hope someone didn't fall for that and pour some money into this...

**Comment by TomTom101** [comment]
Fully agree @illtellyoulater After diving in why an existing config.json cannot be found, I am finding hardcoded paths to `/root` and lots of messed up code. Gave up here.

**Comment by paulogaspar** [comment]
why is this issue closed? I'm still facing this problem, removing the folder and rerunning doesn't work, I get a weird: Read-only file system: '/root'
probably related with the comment above.

**Comment by eginhard** [comment]
This is now fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`
