### ISSUE TITLE
[Bug] 'zh-cn' can speak English, but 'en' can't speak Chiense

### ISSUE THREAD

**Issue by yhyu13** [coqui-ai/TTS#3295]
### Describe the bug

I am expecting that any language speaker can speak any language, meaning we can simply give 'auto' to the language argument. And let the model figure out what languages to speak.

But I found when setting the same sentense "世界，hello" to 'zh-cn', it can speak English word. But when set 'en', it cannot speak Chinese word.

### To Reproduce

run my test1.py script in my forked repo:

https://github.com/yhyu13/TTS/blob/main/my_test/test1.py

And change speakers to the followings
```
speakers = [
        {
        "speaker_wav" : os.path.join(os.getenv("TTS_HOME"), "click-the-button-female-speaking-vocal_87bpm_E_major.wav"),
        "language" : 'en',
        "text" : "世界，hello"
    },
        {
        "speaker_wav" : os.path.join(os.getenv("TTS_HOME"), "click-the-button-female-speaking-vocal_87bpm_E_major.wav"),
        "language" : 'zh-cn',
        "text" : "世界，hello"
    },
]
```

Github cannot upload .wav file, Github Sucks!

### Environment

```shell
pip install tts
```

### Additional context

I need someone smarter than me to point to what could went wrong. Or is it a mistake on my expectation? Should we expect that tts simply recognize all languages that it can speak and speak them out correctly? 

Thanks!

**Comment by erogol** [comment]
Based on your language selection, you internally set the way it pre-processes the text input. When it is set zh-cn input text is converted by pinyin. So probably pinyin works fine with en inputs.

But when en is set then Chinese characters are not even recognized since they are not part of the models vocabulary. 

As a workaround we can try to detect the language for each word and set the text processing accordingly. But I am sure that it would cause some other issues. 

Or we should train Chinese again without using pinyin. 

If someone has a better solution, I am all ears.

**Comment by erogol** [comment]
BTW if you can enter Chinese as pinyin directly along side with English text, things should work.

**Comment by stuartofmine** [comment]
I met this too. Azure TTS works well in the same sentence, I don't know how they overcame this, maybe just by detecting the language of characters or word?

**Comment by jingyibo123** [comment]
Seems like in "zh-cn" language mode, the model can handle english words, but not english characters.
Example: 
`将A节点和B节点合并成为一个统一的U节点`。

The model simply ignores the english symbols `A`, `B` and `U`
