### ISSUE TITLE
'TTS' object has no attribute 'speakers'[Bug] 

### ISSUE THREAD

**Issue by seetimee** [coqui-ai/TTS#3456]
### Describe the bug

'TTS' object has no attribute 'speakers' ,the soure code is `from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker="Ana Florence",
                language="en",
                split_sentences=True
                )
print(tts.speakers)`   but speaker="Ana Florence", can run successfull

### To Reproduce

from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker="Ana Florence",
                language="en",
                split_sentences=True
                )
print(tts.speakers)

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla T4"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023"
```

**Comment by volkovwashere** [comment]
@seetimee
I was facing a similar issue this morning, and found that the bug is due to the following:
when you try to access tts(model).speakers the following get's called
`return None if not self.is_multi_speaker else self.synthesizer.tts_model.speaker_manager.speaker_names`
If you try to directly access and call the following:
`tts(model).synthesizer.tts_model.speaker_manager.speaker_names` you get the following error that was silent before:
`return list(self.name_to_id.keys())` AttributeError: 'dict_keys' object has no attribute 'keys' (under the speaker_names property in the manager class). The issue is because self.name_to_id is already a dict.keys() object, therefore it fails. How you can solve the issue until it is fixed is just simply go to the SpeakerManager class, find the speaker_names property and remove the .keys() part from the list(self.name_to_id.keys()) and it will work.

**Comment by seetimee** [comment]
@volkovwashere  Thanks bro.It works. I directly used the list(tts.synthesizer.tts_model.speaker_manager.name_to_id)  to get the speaker_names results.

**Comment by eginhard** [comment]
I've fixed this in our fork: https://github.com/idiap/coqui-ai-TTS
