### ISSUE TITLE
[Bug] Model won't download

### ISSUE THREAD

**Issue by mprytoluk** [coqui-ai/TTS#3543]
### Describe the bug

I'm trying to run TTS but the model simply won't download.

My code is as follows:

```python
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
```

But the output is simply:
`Downloading model to /home/MYUSER/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2`
No significant network activity is detected, and no error is presented.

Tried reinstalling TTS to no avail.

### To Reproduce

Run

```python
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
```

### Expected behavior

The model should download, or at least provide relevant error information.

### Environment

```shell
{
    "CUDA": {
        ...
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#202312091251-Ubuntu SMP PREEMPT_DYNAMIC Sat Dec  9 14:02:34 UTC"
    }
}
```

**Comment by omenius** [comment]
I'm also unable to download the model with the code above.

Getting error for self signed ssl cert:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /hf-coqui/XTTS-v2/main/model.pth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))`

edit: this error comes from pfsense firewall actually blocking the url via DNSBL_Firebog_Trackers.

**Comment by mprytoluk** [comment]
Update: I just let the cell run for some time and it worked, although I'm not sure why the download did not start immediately.
