### ISSUE TITLE
[Feature request] prosody rate, style emotions, expressiveness, aggressiveness, pace, etc.

### ISSUE THREAD

**Issue by andrewarrow** [coqui-ai/TTS#437]
The [resemble.ai](https://www.resemble.ai) system has markup like:

```
<prosody rate="45%"><style emotions="expressiveness:0.9
aggressiveness:0.5 pace:0.2">
<say-as interpret-as="characters">Zeuxis</style></say-as>
```

Is this open sourced in coqui?

**Comment by AndrewBarfield** [comment]
I've been thinking about the same. Especially speech rate.

I've also come across some text that isn't read correctly, like number ranges (i.e., 400-750) and acronyms (i.e., MPH). This could be interpreted correctly via mark-up configuration.

**Comment by erogol** [comment]
This level of detail is not possible with coqui TTS yet due to the limits of the open datasets.

Depending on which model you use, it might struggle with the acronyms and numbers too.  

These are limitations due to the use of a publicly available dataset.  Most commercial systems use specially created TTS datasets.

**Comment by erogol** [comment]
That's true. Some of the models we release use Phonemes and a text front-end to do the work. You might like to try them. 

The only model that only use characters is ```tts_models/en/ljspeech/tacotron2-DDC``` the rest is more robust to such variations.

Hopefully we'll update this mode soon to use a more advance front end.
